
package com.ipartek.formacion.uf2215clientews.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteServicio", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteServicio {


    /**
     * 
     * @return
     *     returns java.util.List<com.ipartek.formacion.uf2215clientews.cliente.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientes", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.GetClientes")
    @ResponseWrapper(localName = "getClientesResponse", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.GetClientesResponse")
    @Action(input = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/getClientesRequest", output = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/getClientesResponse")
    public List<Cliente> getClientes();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ipartek.formacion.uf2215clientews.cliente.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "putCliente", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.PutCliente")
    @ResponseWrapper(localName = "putClienteResponse", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.PutClienteResponse")
    @Action(input = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/putClienteRequest", output = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/putClienteResponse")
    public Cliente putCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ipartek.formacion.uf2215clientews.cliente.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCliente", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.GetCliente")
    @ResponseWrapper(localName = "getClienteResponse", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.GetClienteResponse")
    @Action(input = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/getClienteRequest", output = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/getClienteResponse")
    public Cliente getCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCliente", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.DeleteCliente")
    @ResponseWrapper(localName = "deleteClienteResponse", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.DeleteClienteResponse")
    @Action(input = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/deleteClienteRequest", output = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/deleteClienteResponse")
    public void deleteCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ipartek.formacion.uf2215clientews.cliente.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postCliente", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.PostCliente")
    @ResponseWrapper(localName = "postClienteResponse", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", className = "com.ipartek.formacion.uf2215clientews.cliente.PostClienteResponse")
    @Action(input = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/postClienteRequest", output = "http://serviciosweb.uf2215.formacion.ipartek.com/ClienteServicio/postClienteResponse")
    public Cliente postCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

}
