
package com.ipartek.formacion.uf2215clientews.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClienteServicioImplService", targetNamespace = "http://serviciosweb.uf2215.formacion.ipartek.com/", wsdlLocation = "http://localhost:8080/clienteservicio?wsdl")
public class ClienteServicioImplService
    extends Service
{

    private final static URL CLIENTESERVICIOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTESERVICIOIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTESERVICIOIMPLSERVICE_QNAME = new QName("http://serviciosweb.uf2215.formacion.ipartek.com/", "ClienteServicioImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/clienteservicio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTESERVICIOIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTESERVICIOIMPLSERVICE_EXCEPTION = e;
    }

    public ClienteServicioImplService() {
        super(__getWsdlLocation(), CLIENTESERVICIOIMPLSERVICE_QNAME);
    }

    public ClienteServicioImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTESERVICIOIMPLSERVICE_QNAME, features);
    }

    public ClienteServicioImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTESERVICIOIMPLSERVICE_QNAME);
    }

    public ClienteServicioImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTESERVICIOIMPLSERVICE_QNAME, features);
    }

    public ClienteServicioImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteServicioImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteServicio
     */
    @WebEndpoint(name = "ClienteServicioImplPort")
    public ClienteServicio getClienteServicioImplPort() {
        return super.getPort(new QName("http://serviciosweb.uf2215.formacion.ipartek.com/", "ClienteServicioImplPort"), ClienteServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteServicio
     */
    @WebEndpoint(name = "ClienteServicioImplPort")
    public ClienteServicio getClienteServicioImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviciosweb.uf2215.formacion.ipartek.com/", "ClienteServicioImplPort"), ClienteServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTESERVICIOIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTESERVICIOIMPLSERVICE_EXCEPTION;
        }
        return CLIENTESERVICIOIMPLSERVICE_WSDL_LOCATION;
    }

}
