openapi: 3.0.1
info:
  title: Ipartekify
  description: Ejemplo de REST para curso
  version: 3.0.0
servers:
  - url: 'http://localhost:8080/api/v3'
    description: Spring REST LOCAL
    variables: {}
tags:
- name: "usuarios"
- name: "artistas"
paths:
  '/usuarios/{id}':
    get:
      tags:
      - "usuarios"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: No encontrado
    put:
      tags:
      - "usuarios"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
    delete:
      tags:
      - "usuarios"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'Borrado'
  /usuarios:
    get:
      tags:
      - "usuarios"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      tags:
      - "usuarios"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
  '/artistas/{id}':
    get:
      tags:
      - "artistas"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        '404':
          description: No encontrado
    put:
      tags:
      - "artistas"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
    delete:
      tags:
      - "artistas"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'Borrado'
  /artistas:
    get:
      tags:
      - "artistas"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Artista'
    post:
      tags:
      - "artistas"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
        rol:
          type: string
    Artista:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        informacion:
          type: string
